language: python

sudo: required
dist: trusty

python:
- 3.6

services:
  - docker

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - docker build -t pyblish/pyblish-qml .
  - docker run --rm -v $(pwd):/pyblish-qml pyblish/pyblish-qml

  # Test setup.py
  - pip install --upgrade --force-reinstall file://$(pwd)

deploy:
  provider: pypi
  user: mottosso
  distributions: "sdist bdist_wheel"
  password:
    secure: NKekJIgRr/kaDXsK6Vz4rj3Uuxk6gK1NsrlAkAqXX8bPSS2oLpp8KVN2SjoCizwdO+sZzry6q0WdbeqnqRwiTTdnotlyVqjbmFNfTCeRdqZKAqYDvfSe44eNWCQgf06zl0lErX9NrJuPnJWyXqutvojdm50b99NzkiO60I+Fr6M=
  on:
    tags: true
    repo: pyblish/pyblish-qml
